SET C51INC=d:\cccc2020\TOOL\Keil\C51\Inc;d:\cccc2020\TOOL\Keil\C51\Inc\Holychip
SET C51LIB=d:\cccc2020\TOOL\Keil\C51\Lib
SET CPU_TYPE=HC89S003F4
SET CPU_VENDOR=HC89S Series
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x01E84800
"d:\cccc2020\TOOL\Keil\C51\BIN\A51.EXE" @.\Objects\STARTUP._ia
"d:\cccc2020\TOOL\Keil\C51\BIN\C51.EXE" @.\Objects\HC-MCU-XBR.__i
"d:\cccc2020\TOOL\Keil\C51\BIN\C51.EXE" @.\Objects\mcu_api.__i
"d:\cccc2020\TOOL\Keil\C51\BIN\C51.EXE" @.\Objects\protocol.__i
"d:\cccc2020\TOOL\Keil\C51\BIN\C51.EXE" @.\Objects\system.__i
"d:\cccc2020\TOOL\Keil\C51\BIN\BL51.EXE" @.\Objects\HC-MCU-XBR.lnp
"d:\cccc2020\TOOL\Keil\C51\BIN\OH51.EXE" ".\Objects\HC-MCU-XBR" 
